Repository irwin-nikk/hci-course-project, pull requests merged in 2019-12, with the labels that each got.

#25 Grid Layout
  pybank/pyqt5_training/advanced_widgets/grid_layout.py
  pybank/training.py
Labels: training

#26 Progress Bar
  pybank/pyqt5_training/advanced_widgets/progress_bar.py
  pybank/training.py
Labels: training

#27 Sign-up complete
  pybank/app_code/sign_in.py
  pybank/app_code/sign_up.py
  pybank/assets/icons8-eye-24.png
  pybank/assets/icons8-unchecked-radio-button-24 (1).png
  pybank/assets/icons8-unchecked-radio-button-24.png
  pybank/customer_data/overview.json
  pybank/main.py
  pybank/pyqt5_global/stylesheet.qss
Labels: enhancement, gui

#28 Account Overview
  pybank/app_code/account_overview.py
Labels: gui

#29 Updated README and .gitignore
  .gitignore
  README.md
Labels: documentation

#30 Account Overview
  pybank/app_code/account_overview.py
  pybank/app_code/sign_in.py
  pybank/app_code/sign_up.py
Labels: enhancement, gui

#31 Changed tab colors for readability.
  pybank/pyqt5_global/stylesheet.qss
Labels: gui

#32 Simple, static graph page added.
  pybank/app_code/account_overview.py
  pybank/app_code/graphs.py
  pybank/customer_data/overview.json
  pybank/customer_data/r/checking.csv
  pybank/customer_data/test1/checking.csv
  pybank/main.py
Labels: enhancement, gui

#33 Account Overview Navigation Menu
  Pipfile
  Pipfile.lock
  pybank/app_code/account_overview.py
  pybank/app_code/nav_menu.py
  pybank/main.py
Labels: enhancement

#34 Account Overview
  pybank/app_code/account_overview.py
  pybank/customer_data/nikk/checking.csv
  pybank/customer_data/nikkolas irwin/checking.csv
  pybank/customer_data/overview.json
  pybank/customer_data/test/checking.csv
Labels: enhancement

#35 Stylesheet update for navigation bar
  pybank/pyqt5_global/stylesheet.qss
Labels: gui

#36 Account Overview
  pybank/app_code/account_overview.py
  pybank/app_code/graphs.py
  pybank/main.py
Labels: enhancement, gui, visualizations
